### PR TITLE
ci-requirements.js file replaced with ci-requirements.sh file

### PR DESCRIPTION
**Pull request by manjots1607**
What this PR does
This PR converts ci-requirements.sh file to ci-requirements.js file. This is in response to issue #174.

Changes you made
I deleted the previously written bash file and written a .js file using shelljs module to execute bash commands.
updated "npm run cirequirements" command in package.json, so as .js file would run when it is called. 

Screenshot/ CodeSnippet
Not required

### CODE REVIEW

**Comment by manjots1607** [comment]
@umeshp7 @shreys7
Please review

**Comment by sastava007** [comment]
@manjots1607 Have not I mentioned that I'm already working on this?

**Comment by umeshp7** [comment]
There are conflicts. Please rebase with the latest develop. 
Also there are indentation differences in these changes as compared to the rest of the repo. Please fix those after rebasing with the latest develop.

**Comment by manjots1607** [comment]
Thanks For Review, I will resolve issues as soon as possible.

**Comment by manjots1607** [comment]
Unexpected error in travis CI please check @umeshp7

**Comment by manjots1607** [comment]
Fixed Error by replacing:-
"npm install shelljs" to "npm install"
in Travis CI.
please review it again @umeshp7 .

**Comment by manjots1607** [comment]
Please review it @umeshp7 @shreys7

**Comment by webholik** [comment]
I am not convinced that we need to replace the `ci-requirements.sh` with javascript. It will not make the code more portable - we are still running `apt-get` which is only available on Debian based Linux distributions. On the other hand it causes problem if you are running the script on your local machine. `shelljs` does not provide a `tty` to commands so there is no way to give interactive input to them. This can be problem, for example, for `java-okhttp` codegen, if you already have the required jar files installed, the `unzip` command will ask interactively if you want to replace them. There is no way to send a reply so the script just hangs there. 

I think we should stick to the shell script for now until we have a better solution.

**Comment by webholik** [comment]
Closing this as ci-requirements.sh will be kept as bash script.

**Pull request closed without merging**
