### PR TITLE
Nodejs-axios generator [WIP]

### PR DESCRIPTION
**Pull request by emanuelet**
Hi, I'm working on the generator for axios (should actually work for browser and NodeJS). I will apprecciate some help to fix and setup the tests properly

### CODE REVIEW

**Comment by darkCavalier11** [comment]
sure. happy to help..

**Comment by shreys7** [comment]
@emanuelet sure, tell us what help do you need.

**Comment by emanuelet** [comment]
So I guess the first part where I'm not sure what I'm doing is how to setup the newman tests

**Comment by umeshp7** [comment]
@emanuelet You could check how newman-tests are run for other JS code gens. 
For example, you could look into how js-fetch runs Newman test. It should be very similar to what you need for Axios.

**Comment by umeshp7** [comment]
https://github.com/postmanlabs/postman-code-generators/issues/135

**Comment by umeshp7** [comment]
https://travis-ci.com/postmanlabs/postman-code-generators/builds/150137190#L6088
Tests failing^

**Comment by shreys7** [comment]
Closing due to inactivity. Feel free to open another PR after fixing the failing tests.

**Pull request closed without merging**
