### PR TITLE
Converted test.sh bash script to Javascript

### PR DESCRIPTION
**Pull request by sastava007**
**What this PR does**
This PR converts the `test.sh` bash script file to javascript making it the platform agnostic. This PR is part of a series of PRs trying to solve issue #174 

**Changes you made**
Converted the bash commands into it's closely equivalent JS commands using `shellJS` package.

**Screenshot/ CodeSnippet**
Not required

**Test Configuration**:
Tried to test locally for various codegens by running `npm test <codegen-name>` and comparing the result obtained with that generated from the similar bash script.

**Follow up**
Not required

*Thanks for contributing!* ❤️

### CODE REVIEW

**Comment by sastava007** [comment]
@umeshp7 @shreys7 Please review!

**Comment by umeshp7** [comment]
There are some conflicts here. @sastava007

**Comment by sastava007** [comment]
@umeshp7 Yeah, I saw that coming yesterday. It's because I removed **test.sh** file, I tried to fix it on my end but I don't have write access to repo that's why I can't resolve. 
Can you please look at your end if you can fix it?

And this is also the reason why Travis build is also not completing.

**Comment by sastava007** [comment]
@shreys7 Can you please help me with resolving conflict on this PR?

**Comment by umeshp7** [comment]
Have you tried rebasing with the develop? @sastava007

**Comment by sastava007** [comment]
@umeshp7 Okay, then let me first pull and merge the latest changes in develop and then create the commit.

**Pull request closed without merging**
