### PR TITLE
Add: Eslint in root files/folders

### LINKED ISSUE #166: Adding eslint in system tests
All code-generators have their own eslint check but there are no eslint for `lib`, `test`, `npm` and `index.js`.
Add eslint checks to the root files and folders apart from `codegen` folder.

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**
Fixes #166 
Check issue comments for description

### CODE REVIEW

**Comment by VibhorCodecianGupta** [comment]
@umeshp7 added linting, however there are a lot errors that cause a process exit. Shall I push a commit fixing them as well?

**Comment by umeshp7** [comment]
@VibhorCodecianGupta Yes, it would be good to have those fixes as well.

**Comment by VibhorCodecianGupta** [comment]
@umeshp7 fixed lint errors except one, `test/codegen/structure.test.js` line 44 violates max length, not sure how you'd like to fix that (break the string in newline?). Also, `npm run test` fails at newman tests for basicCollection, it gives a `ENOENT` for all the tests in the block

**Comment by shreys7** [comment]
@VibhorCodecianGupta you can split the line 44 into two strings, the second one on a new line. For the `ENOENT` failure, can you share the exact error? and for which codegen it is failing?

**Comment by umeshp7** [comment]
Some tests are failing here: https://travis-ci.com/postmanlabs/postman-code-generators/builds/150958863#L2505

**Comment by umeshp7** [comment]
The test that is failing is due to a duplicate copy of a dependency `postman-collection`. Remove it from `devDependencies` and it should be pass. @VibhorCodecianGupta

**Comment by umeshp7** [comment]
@VibhorCodecianGupta any updates on this? We'll have to close this soon due to inactivity.

**Comment by VibhorCodecianGupta** [comment]
@shreys7 @umeshp7 so `no-multi-str` is also enabled in .eslintrc, which makes splitting strings in multiple lines erroneous. I think you should follow either of the length/multi string check, suggestions?
Also I had my midterms, I'll resolve this issue asap and push

**Comment by VibhorCodecianGupta** [comment]
@umeshp7 @shreys7 update, rebasing will resolve `enoent` failures. 
> @shreys7 @umeshp7 so no-multi-str is also enabled in .eslintrc, which makes splitting strings in multiple lines erroneous. I think you should follow either of the length/multi string check, suggestions?

This issue still remains though. How to proceed?

**Pull request merged**
