### PR TITLE
Perform installation according to package manager

### PR DESCRIPTION
**Pull request by aman-v-singh**
- Used [detect-package-manager](https://www.npmjs.com/package/detect-package-manager) to detect and use the proper package manager for installation

### CODE REVIEW

**Comment by patricksevat** [comment]
@opicacek could you connect with @aman-v-singh to test out the beta version?

**Comment by aman-v-singh** [comment]
I have published the beta version [1.10.1-beta.0](https://www.npmjs.com/package/postman-code-generators/v/1.10.1-beta.0).

**Comment by opicacek** [comment]
@aman-v-singh I tried to do the upgrade locally to the version `1.10.1-beta.1`, the installation was successful. In my case the `yarn` was used. Additional dependencies in `codegens` were also installed. 👍

**Comment by VShingala** [comment]
@aman-v-singh Let's look into failing tests and get this merged.

**Comment by aman-v-singh** [comment]
> @aman-v-singh Let's look into failing tests and get this merged.

Test fixed in this PR.
https://github.com/postmanlabs/postman-code-generators/pull/745

**Review by VShingala — APPROVED** [review]

**Comment by robbieaverill** [comment]
Would love to see this in a tagged release - I believe it will fix an issue I am having with installing in a monorepo (using pnpm)

**Comment by robbieaverill** [comment]
@aman-v-singh would you be able to release a new beta tag, please?

**Comment by VShingala** [comment]
@robbieaverill This is now available with v1.11.0. http://npmjs.com/package/postman-code-generators/v/1.11.0

**Pull request merged**
