### PR TITLE
[WIP] Adds nodejs-axios codegen support

### LINKED ISSUE #135: Can you please add the support for axios

### PR DESCRIPTION
**Pull request by someshkoli**
Closes #135 
Adds support for axios codegen as requested in #135

### CODE REVIEW

**Comment by fjufju** [comment]
what about https://github.com/postmanlabs/postman-code-generators/pull/232?
Is this somehow similar?

**Comment by someshkoli** [comment]
> what about https://github.com/postmanlabs/postman-code-generators/pull/232?
> Is this somehow similar?

I guess. I haven't tested out his version yet

**Comment by fjufju** [comment]
There is also https://github.com/postmanlabs/postman-code-generators/pull/226.
@someshkoli do you know who from members can review this?
I really want axios code generator

**Comment by someshkoli** [comment]
> There is also #226.
> @someshkoli do you know who from members can review this?
> I really want axios code generator

I'm not sure

**Comment by fjufju** [comment]
@ajwad-shaikh could you please take a look at this.
Axios support would be awesome, especially for React developers

**Comment by ajwad-shaikh** [comment]
@fjufju I would love to take a look, but I don't think it'll make a difference. The PR requires an approving review from one of the maintainers and I'm just another contributor.

My own PR #238 is awaiting review for about a month now. The maintainers are having a tough time dealing with the shift to remote working practices.

I suppose @shreys7 will be happy to take a look at this as soon as he finds time.

**Comment by someshkoli** [comment]
Yeah the maintainers will look into it when they have time. As a work around, y'all can use a tool that I built [checkout](https://github.com/someshkoli/collection-SDK-generator). It doesn't have axios support yet bt if you really want it I'll be happy to add it. it'll barely an hour for me to add axios to it.

**Comment by shreys7** [comment]
Hey @someshkoli. below is an example of Nodejs-Request snippet generation
```
var request = require('request');
var options = {
  'method': 'POST',
  'url': 'https://postman-echo.com/post',
  'headers': {
    'Content-Type': ['text/html', 'text/plain']
  },
  body: "<html>\n  Test Test !@#$%^&*()+POL:},'';,[;[;\n</html>"

};
request(options, function (error, response) {
  if (error) throw new Error(error);
  console.log(response.body);
});
``` 
Similarly, if you notice Nodejs-Native snippets, we follow the same construct, i.e. define a option/configuration object before and then pass it to the actual library sdk function. Thus, we would like to use that syntax for axios too. e.g.
```
const axios = require('axios');
const data = "sample data";

const config = {
  'method': 'post',
  'url': 'https://postman-echo.com/post',
  'headers': {        
   'Content-Type': 'text/html, text/plain'
  },
  data : data
}
axios(config)
.then(function (response) {
  console.log(JSON.stringify(response.data));
})
.catch(function (error) {
  console.log(error);
});
```

I will review it once again once you change the code generation to follow the above construct. I have some other comments too, will let you know once these changes are done. 🙂

**Comment by someshkoli** [comment]
> Hey @someshkoli. below is an example of Nodejs-Request snippet generation
> ```
> var request = require('request');
> var options = {
>   'method': 'POST',
>   'url': 'https://postman-echo.com/post',
>   'headers': {
>     'Content-Type': ['text/html', 'text/plain']
>   },
>   body: "<html>\n  Test Test !@#$%^&*()+POL:},'';,[;[;\n</html>"
> 
> };
> request(options, function (error, response) {
>   if (error) throw new Error(error);
>   console.log(response.body);
> });
> ``` 
> Similarly, if you notice Nodejs-Native snippets, we follow the same construct, i.e. define a option/configuration object before and then pass it to the actual library sdk function. Thus, we would like to use that syntax for axios too. e.g.
> ```
> const axios = require('axios');
> const data = "sample data";
> 
> const config = {
>   'method': 'post',
>   'url': 'https://postman-echo.com/post',
>   'headers': {        
>    'Content-Type': 'text/html, text/plain'
>   },
>   data : data
> }
> axios(config)
> .then(function (response) {
>   console.log(JSON.stringify(response.data));
> })
> .catch(function (error) {
>   console.log(error);
> });
> ```
> 
> I will review it once again once you change the code generation to follow the above construct. I have some other comments too, will let you know once these changes are done. 🙂

Sure I'll add these changes

**Comment by someshkoli** [comment]
I have made the above changes and made a new PR as this one has some additional unwanted changes.  #245

**Pull request closed without merging**
