### PR TITLE
Converted package.sh and zip.sh to Javascript files.

### PR DESCRIPTION
**Pull request by sastava007**
**What this PR does**
This PR converts the `package.sh`and `zip.sh` bash script file to javascript making it the platform agnostic. This PR is last in the series of PRs trying to solve issue #174 

**Changes you made**
Converted the bash commands into it's closely equivalent JS commands using `shellJS` npm package.

**Screenshot/ CodeSnippet**
Not required

**Test Configuration**:
Tried to test locally for various codegens by running `npm package <codegen-name>` and comparing the result obtained with that generated from the similar bash script.

**Follow up**
Not required

*Thanks for contributing!* ❤️

### CODE REVIEW

**Comment by sastava007** [comment]
@umeshp7 @codenirvana  Please review!

**Comment by sastava007** [comment]
@umeshp7 @codenirvana @abhijitkane Please review!

**Comment by sastava007** [comment]
@shreys7 Can you please review this one too?🥺

**Comment by sastava007** [comment]
@umeshp7 Sir can you please have a look and review?

**Comment by sastava007** [comment]
@umeshp7 Any updates?
Though the build test is passing which means that there's no problem with my code, but the PR test is failing but I can't find any reason why it's not able to find PR/201 branch?

**Comment by shreys7** [comment]
@sastava007 Can you try cherrypicking the commits onto another branch, close this PR and create a new PR?

**Pull request closed without merging**
