### PR TITLE
Maven Address Changed to solve Build error  & try-catch added to lib/index.js

### LINKED ISSUE #167: Exception handling for index functions
Add some level of exception handling(try-catch blocks) for functions inside `lib` folder.

### LINKED ISSUE #179: Build on Travis CI failing on most of PR's
**Describe the bug**
I am a beginner and solved my first issue and made PR but build failed for that PR, then I observe most of PR are failing and checked details on Travis CI and by observing terminal output I think this is due to the exactly same reason for each PR.

**To Reproduce**
1. Do Some Changes on the forked repository.
2. Make Pull Request.
3. Checks would be failed due to build failed on Travis CI. 

**Expected code snippet and corresponding request**
I have tried to solve it and think it is due to the address of the maven repository i.e http://central.maven.org as it results in NOT FOUND.

**Screenshots**
Capture
Capture2
Capture3

http://central.maven.org

Capture4

### PR DESCRIPTION
**Pull request by manjots1607**
Fixes #167 
Fixes #179

### CODE REVIEW

**Comment by sastava007** [comment]
@manjots1607 Try to create separate PR for both of your commits, as they are solving different issues that are nowhere related to each other. This would help the maintainers to review your code more easily.

**Comment by shreys7** [comment]
Correct @sastava007. Also, the PR is still failing for a specific case of `follow redirect` request in java-okhttp. The request is getting timed out after 60 seconds. Can you take a look at what is the root cause that it is getting no response for `follow redirects` request @manjots1607?

**Comment by manjots1607** [comment]
@shreys7 I would love to work on this. As I am new to opensource contributions I will consider what @sastava007 has said and I will be submit two separate PR.

**Comment by umeshp7** [comment]
@manjots1607 Hi, closing this for now. 
There should be two separate PRs as already mentioned.

There is already a PR exploring Maven issues no need for another PR. 
Also, we can not rely on repo1.maven.org as well since that could be moved without notice. 

For try-catch:
You need to identify where the  unexpected exceptions could occur and add try-catch for those.

**Pull request closed without merging**
