### PR TITLE
Add in C# HttpClient code generation

### LINKED ISSUE #452: Add Support for C# HttpClient code gen
**Is your feature request related to a problem? Please describe.**

I would love if Postman had the ability to generate code for making HTTP calls using the built in [`HttpClient`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-5.0) in `System.Net.Http`. Some companies have requirement to not use outside packages so using only things built into .NET could be helpful.  

**Describe the solution you'd like**

I would like it to generate code as close to the best practices as described by Microsoft and shown in this [example](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-5.0#examples).

**Additional context**

I am going to personally start working on this and will hopefully be referencing this issue in a pull request soon.

### PR DESCRIPTION
**Pull request by justindbaur**
Fixes #452 

This PR adds a C# code gen that does not rely on any 3rd party libraries. The core item it uses is [`HttpClient`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-5.0) for making the call. 

Some examples of it's code gen are below:

GET Request with headers:
```csharp
var client = new HttpClient();
var request = new HttpRequestMessage(HttpMethod.Get, "https://postman-echo.com/headers");
request.Headers.Add("my-sample-header", "Lorem ipsum dolor sit amet");
request.Headers.Add("TEST", "@#$%^&*()");
request.Headers.Add("more", ",./';[]}{\":?><|\\\\");
var response = await client.SendAsync(request);
response.EnsureSuccessStatusCode();
Console.WriteLine(await response.Content.ReadAsStringAsync());
```

Simple GET
```csharp
var client = new HttpClient();
var request = new HttpRequestMessage(HttpMethod.Get, "https://postman-echo.com/get?test=123&anotherone=232");
var response = await client.SendAsync(request);
response.EnsureSuccessStatusCode();
Console.WriteLine(await response.Content.ReadAsStringAsync());
```

Plaintext POST
```csharp
var client = new HttpClient();
var request = new HttpRequestMessage(HttpMethod.Post, "https://postman-echo.com/post");
var content = new StringContent("Duis posuere augue vel cursus pharetra. In luctus a ex nec pretium. Praesent neque quam, tincidunt nec leo eget, rutrum vehicula magna.\nMaecenas consequat elementum elit, id semper sem tristique et. Integer pulvinar enim quis consectetur interdum volutpat. !@#$%^&*()_+-=,.<>/?", null, "text/plain");
request.Content = content;
var response = await client.SendAsync(request);
response.EnsureSuccessStatusCode();
Console.WriteLine(await response.Content.ReadAsStringAsync());
```

JSON POST
```csharp
var client = new HttpClient();
var request = new HttpRequestMessage(HttpMethod.Post, "https://postman-echo.com/post");
var content = new StringContent("{\n  \"json\": \"Test-Test\"\n}", null, "application/json");
request.Content = content;
var response = await client.SendAsync(request);
response.EnsureSuccessStatusCode();
Console.WriteLine(await response.Content.ReadAsStringAsync());
```

Url Encoded POST
```csharp
var client = new HttpClient();
var request = new HttpRequestMessage(HttpMethod.Post, "https://postman-echo.com/post");
var collection = new List<KeyValuePair<string, string>>();
collection.Add(new("1", "'a'"));
collection.Add(new("2", "\"b\""));
collection.Add(new("'3'", "c"));
collection.Add(new("\"4\"", "d"));
collection.Add(new("Special", "!@#$%*()^_=`&~              "));
collection.Add(new("more", ",./';[]}{\":?><|\\\\    "));
collection.Add(new("non-ascii", "테스트"));
var content = new FormUrlEncodedContent(collection);
request.Content = content;
var response = await client.SendAsync(request);
response.EnsureSuccessStatusCode();
Console.WriteLine(await response.Content.ReadAsStringAsync());
```

Form with files
```csharp
var client = new HttpClient();
var request = new HttpRequestMessage(HttpMethod.Post, "https://postman-echo.com/post");
var content = new MultipartFormDataContent();
content.Add(new StreamContent(File.OpenRead("./dummyFile1.txt")), "single file", "./dummyFile1.txt");
content.Add(new StreamContent(File.OpenRead("./dummyFile2.txt")), "multiple files", "./dummyFile2.txt");
content.Add(new StreamContent(File.OpenRead("./dummyFile3.txt")), "multiple files", "./dummyFile3.txt");
request.Content = content;
var response = await client.SendAsync(request);
response.EnsureSuccessStatusCode();
Console.WriteLine(await response.Content.ReadAsStringAsync());
```

### CODE REVIEW

**Review by aliramadan8 — APPROVED** [review]

**Comment by Misiu** [comment]
any updates?

**Comment by akshaydeo** [comment]
@Misiu We will get it reviewed in the upcoming week

**Comment by Misiu** [comment]
@akshaydeo awesome news! Looking forward to this option in Postman 🤞

**Comment by justindbaur** [comment]
Thank you so much, @akshaydeo, I will try and get it updated so there are no merge conflicts!

**Review by webholik — APPROVED** [review]

**Comment by Misiu** [comment]
@webholik thank you for merging this. What's the next step? When can it be available in postman?

**Comment by webholik** [comment]
@Misiu It will be available in the next release of Postman. I'll inform you in this thread once it's out.

**Comment by Misiu** [comment]
It's available in version 10.10.6 🎉🎉🎉

**Pull request merged**
