### PR TITLE
Fixed Issue causing Travis Build fail

### PR DESCRIPTION
**Pull request by nikhilmuz**
Changes
- Updated maven repo URLs in CI requirements bash script for Travis.
- Mocha timeout implementation increased to 100 seconds for okhttp causing timeout error.

### CODE REVIEW

**Comment by nikhilmuz** [comment]
@umeshp7 Approval required. Compare it with #171 before merging.
Primary differences are:
- Time duration is 100 sec rather than 120 sec in mentioned PR.
- I have updated the broken URLs rather than including them in repository close this if that is more suitable.

**Comment by umeshp7** [comment]
@nikhilmuz
Using repo1.maven.org is not a good idea since that could also change without notice (this name seems temporary too).
It does increase the repo size but it's a one time expense. We could find a better solution in the future, with specific test environments for each code-gen for more rigorous tests.

Also, increasing timeout time does not solve the primary issue. The time it is taking to finish execution could be a problem with the code we have generated. The aim is not to pass the test, but to produce accurate code-snippets.
I am trying a fix with mockbin's request, hope that works since I don't see any issues with the java-okhttp code-generated for redirects.

**Comment by nikhilmuz** [comment]
@umeshp7 I was wondering why we ain't using some SDK by maven to get links?

**Comment by umeshp7** [comment]
We would be interested in that. Any such SDK in your mind that you suggest? @nikhilmuz

**Comment by nikhilmuz** [comment]
@umeshp7 [Apache Maven Download](http://maven.apache.org/download.cgi) is this what you are referring to? Actually it is included in the project for dependency management and an XML file keeps list of dependency and version. I should create a feature request in GitHub issues I guess if it is worth a try.

**Comment by umeshp7** [comment]
Feel free to create a PR for this fix, we would be happy to review. 

Taking this discussion on the above issues and closing this thread.

**Pull request closed without merging**
