### PR TITLE
[FIX] libcurl: Free up headers list to prevent memory leak

### PR DESCRIPTION
**Pull request by aman-v-singh**
- Issue: https://github.com/postmanlabs/postman-app-support/issues/12578

### CODE REVIEW

**Review by VShingala — COMMENTED** [review]
Can we look into failing unit tests and possibly fix them?

**Review by VShingala — APPROVED** [review]

**Comment by VShingala** [comment]
@aman-v-singh changes looks good but tests are still failing.

**Comment by aman-v-singh** [comment]
> @aman-v-singh changes look good but tests are still failing.

@VShingala The unit tests that are failing are unrelated to the changes in this PR. We can probably merge this PR while I parallelly try to resolve most of the issues locally.

**Comment by VShingala** [comment]
> @VShingala The unit tests that are failing are unrelated to the changes in this PR. We can probably merge this PR while I parallelly try to resolve most of the issues locally.

Ok, I'll proceed with merge then.

**Pull request merged**
